"""Differential suite: vol_mojo (native + forced fallback) vs the volatility3 oracle.

The oracle is the published PyPI release volatility3==2.28.2, imported from
PYTHONPATH (``.oracle-volatility3/`` per scripts/test_all_volatility3_hive.sh).
The suite runs twice per scripts/test_all_volatility3_hive.sh: once against
the native kernel, once with VOL_MOJO_DISABLE_NATIVE=1 — both backends must
match the oracle exactly (tuple-for-tuple / hit-for-hit, order included).

Hive fixtures are small valid hives generated by
tests/test_volatility3_hive_fixtures.py — no copyrighted Windows hives are
downloaded or required.
"""

from __future__ import annotations

import pytest

volatility3 = pytest.importorskip("volatility3", reason="oracle not installed")

from test_volatility3_hive_fixtures import (  # noqa: E402
    HiveBuilder,
    add_management,
    fake_nt_isf_json,
    oracle_pool_hits,
    oracle_walk_tuples,
    put_header_x64,
    put_header_x86,
)

import vol_mojo  # noqa: E402
from vol_mojo import PoolConstraint, volatility3_integration  # noqa: E402

BACKEND = (
    "fallback"
    if not vol_mojo.native_available()
    else f"native ({vol_mojo.backend_info()['native_source']})"
)


def _poolscanner():
    """Import the oracle's poolscanner with the cycle-safe import order."""
    from volatility3.framework.symbols.windows.extensions import pool as _poolext  # noqa: F401
    from volatility3.plugins.windows import poolscanner

    return poolscanner


# ---------------------------------------------------------------------------
# Hive fixtures.
# ---------------------------------------------------------------------------


def _write_oracle_image(tmp_path, name, dat, hbins_len):
    isf_path = tmp_path / f"{name}.isf.json"
    isf_path.write_text(fake_nt_isf_json())
    img, cmhive_off = add_management(dat, hbins_len)
    img_path = tmp_path / f"{name}.img"
    img_path.write_bytes(img)
    return str(img_path), cmhive_off, str(isf_path)


@pytest.fixture(scope="module")
def small_tree(tmp_path_factory):
    """ROOT -> lh[Microsoft, Software -> lf[Windows, CurrentVersion]]."""
    b = HiveBuilder()
    leaf1 = b.add_cell(b.nk(b"Microsoft"))
    leaf2a = b.add_cell(b.nk(b"Windows"))
    leaf2b = b.add_cell(b.nk(b"CurrentVersion"))
    idx2 = b.add_cell(b.index(b"lf", [(leaf2a, 0x11111111), (leaf2b, 0x22222222)]))
    mid2 = b.add_cell(b.nk(b"Software", subkey_count=2, subkey_list=idx2))
    idx = b.add_cell(b.index(b"lh", [(leaf1, 0xAAAAAAAA), (mid2, 0xBBBBBBBB)]))
    root = b.add_cell(b.nk(b"ROOT", flags=0x2C, subkey_count=2, subkey_list=idx))
    dat, hbins_len = b.build_dat(root)
    tmp = tmp_path_factory.mktemp("small_tree")
    img, cmhive, isf = _write_oracle_image(tmp, "small", dat, hbins_len)
    return {"dat": dat, "img": img, "cmhive": cmhive, "isf": isf, "root": root}


@pytest.fixture(scope="module")
def ri_nested(tmp_path_factory):
    """ROOT -> ri[lh[c1, c2], ri2[lf[c3, c4]]] — exercises index recursion."""
    b = HiveBuilder()
    c1 = b.add_cell(b.nk(b"ControlSet001"))
    c2 = b.add_cell(b.nk(b"ControlSet002"))
    c3 = b.add_cell(b.nk(b"Services"))
    c4 = b.add_cell(b.nk(b"Enum"))
    lh1 = b.add_cell(b.index(b"lh", [(c1, 0x10101010), (c2, 0x20202020)]))
    lf2 = b.add_cell(b.index(b"lf", [(c3, 0x30303030), (c4, 0x40404040)]))
    ri2 = b.add_cell(b.index(b"ri", [lf2]))
    ri1 = b.add_cell(b.index(b"ri", [lh1, ri2]))
    root = b.add_cell(b.nk(b"ROOT", flags=0x2C, subkey_count=4, subkey_list=ri1))
    dat, hbins_len = b.build_dat(root)
    tmp = tmp_path_factory.mktemp("ri_nested")
    img, cmhive, isf = _write_oracle_image(tmp, "ri", dat, hbins_len)
    return {"dat": dat, "img": img, "cmhive": cmhive, "isf": isf, "root": root}


@pytest.fixture(scope="module")
def dirty_cells(tmp_path_factory):
    """Skippable subkey-list entries + odd names + a multi-hbin tree.

    The lh list of ROOT contains, in order: a valid child, an entry of
    0xFFFFFFFF, an entry pointing at a vk cell, an entry beyond the hive
    storage, three more valid children (one with an empty name, one with
    latin-1 high bytes, one whose SubKeyLists[0] is 0), and a final child
    that fans out to 300 filler subkeys through an ri index — so the
    reachable tree spans several hbins. Both walkers must skip the three
    bad entries silently and keep the order of the good ones.
    """
    b = HiveBuilder()
    vk_cell = b.add_cell(b.vk(b"SomeValue"))
    child_a = b.add_cell(b.nk(b"Alpha"))
    child_empty = b.add_cell(b.nk(b""))
    child_latin = b.add_cell(b.nk(b"S\xe9curit\xe9"))
    child_zero = b.add_cell(b.nk(b"ZeroList", subkey_count=1, subkey_list=0))
    fillers = [b.add_cell(b.nk(f"filler-{i:04d}".encode())) for i in range(300)]
    # Fan the fillers out through ri -> [lh, lh, ...] (40 entries per lh).
    lhs = [
        b.add_cell(
            b.index(b"lh", [(c, 0x1000 + i) for i, c in enumerate(fillers[k : k + 40])])
        )
        for k in range(0, 300, 40)
    ]
    ri = b.add_cell(b.index(b"ri", lhs))
    child_b = b.add_cell(b.nk(b"Beta", subkey_count=300, subkey_list=ri))
    beyond = 0x00F00000  # far outside the generated storage
    idx = b.add_cell(
        b.index(
            b"lh",
            [
                (child_a, 0x1),
                (0xFFFFFFFF, 0x2),
                (vk_cell, 0x3),
                (beyond, 0x4),
                (child_empty, 0x5),
                (child_latin, 0x6),
                (child_zero, 0x7),
                (child_b, 0x8),
            ],
        )
    )
    root = b.add_cell(b.nk(b"ROOT", flags=0x2C, subkey_count=5, subkey_list=idx))
    dat, hbins_len = b.build_dat(root)
    tmp = tmp_path_factory.mktemp("dirty_cells")
    img, cmhive, isf = _write_oracle_image(tmp, "dirty", dat, hbins_len)
    return {
        "dat": dat,
        "img": img,
        "cmhive": cmhive,
        "isf": isf,
        "root": root,
        "storage_len": hbins_len,
    }


# ---------------------------------------------------------------------------
# Hive walk differential tests.
# ---------------------------------------------------------------------------


class TestHiveWalk:
    def test_banner(self):
        print(f"\nvol_mojo backend under test: {BACKEND}")

    def test_small_tree(self, small_tree):
        expected = oracle_walk_tuples(
            small_tree["img"], small_tree["cmhive"], small_tree["isf"]
        )
        got = vol_mojo.walk_hive(small_tree["dat"])
        assert got == expected
        assert [t[2] for t in got] == [
            "ROOT",
            "Microsoft",
            "Software",
            "Windows",
            "CurrentVersion",
        ]

    def test_ri_nested(self, ri_nested):
        expected = oracle_walk_tuples(
            ri_nested["img"], ri_nested["cmhive"], ri_nested["isf"]
        )
        got = vol_mojo.walk_hive(ri_nested["dat"])
        assert got == expected
        assert [t[2] for t in got] == [
            "ROOT",
            "ControlSet001",
            "ControlSet002",
            "Services",
            "Enum",
        ]

    def test_dirty_cells_skipped(self, dirty_cells):
        expected = oracle_walk_tuples(
            dirty_cells["img"], dirty_cells["cmhive"], dirty_cells["isf"]
        )
        got = vol_mojo.walk_hive(
            dirty_cells["dat"], storage_length=dirty_cells["storage_len"]
        )
        assert got == expected
        names = [t[2] for t in got]
        assert names[:6] == ["ROOT", "Alpha", "", "Sécurité", "ZeroList", "Beta"]
        assert names[6:] == [f"filler-{i:04d}" for i in range(300)]
        assert len(got) == 306
        # The reachable tree spans several hbins (multi-page translation).
        assert max(t[0] for t in got) > 0x4000

    def test_subtree_root_override(self, small_tree):
        """visit_nodes(visitor, node=...) from a non-root node must match."""
        full = vol_mojo.walk_hive(small_tree["dat"])
        software = next(t for t in full if t[2] == "Software")
        node_cell = software[0] - 4  # tuple offset is cell index + 4
        expected = oracle_walk_tuples(
            small_tree["img"], small_tree["cmhive"], small_tree["isf"], node_off=node_cell
        )
        got = vol_mojo.walk_hive(small_tree["dat"], root_cell_offset=node_cell)
        assert got == expected
        assert [t[2] for t in got] == ["Software", "Windows", "CurrentVersion"]

    def test_non_regf_signature_uses_0x20(self, tmp_path):
        """A non-'regf' base block makes the oracle use root cell 0x20."""
        b = HiveBuilder()
        only = b.add_cell(b.nk(b"FirstCell"))
        assert only == 0x20
        dat, hbins_len = b.build_dat(0x20)
        dat = bytearray(dat)
        dat[0:4] = b"REGF"  # wrong case: the signature check is case-sensitive
        dat = bytes(dat)
        img, cmhive, isf = _write_oracle_image(tmp_path, "nonregf", dat, hbins_len)
        expected = oracle_walk_tuples(img, cmhive, isf)
        got = vol_mojo.walk_hive(dat)
        assert got == expected == [(0x24, "_CM_KEY_NODE", "FirstCell")]

    def test_storage_bound_truncates_name_raises_both_sides(self, tmp_path, small_tree):
        """Root name beyond the storage bound: the oracle's translation
        raises; so must we (HiveError)."""
        dat = small_tree["dat"]
        root = small_tree["root"]
        # Bound the storage so the root node's name (at cell+4+0x4C) is
        # outside it, while sig/SubKeyLists/NameLength remain inside.
        storage_len = root + 4 + 0x4C - 1
        img, cmhive = add_management(dat, storage_len)
        img_path = tmp_path / "trunc.img"
        img_path.write_bytes(img)
        isf_path = tmp_path / "trunc.isf.json"
        isf_path.write_text(fake_nt_isf_json())
        with pytest.raises(Exception):
            oracle_walk_tuples(str(img_path), cmhive, str(isf_path))
        with pytest.raises(vol_mojo.HiveError):
            vol_mojo.walk_hive(dat, storage_length=storage_len)

    def test_root_not_nk_raises(self, tmp_path):
        """Root cell pointing at a non-nk cell: the oracle raises (the
        visited object has no get_subkeys); we raise HiveError."""
        b = HiveBuilder()
        root = b.add_cell(b.vk(b"NotAKey"))
        dat, hbins_len = b.build_dat(root)
        img, cmhive, isf = _write_oracle_image(tmp_path, "badroot", dat, hbins_len)
        with pytest.raises(Exception):
            oracle_walk_tuples(img, cmhive, isf)
        with pytest.raises(vol_mojo.HiveError):
            vol_mojo.walk_hive(dat)

    def test_integration_helper_matches(self, small_tree):
        got = volatility3_integration.walk_hive_tuples(small_tree["dat"])
        assert got == vol_mojo.walk_hive(small_tree["dat"])


# ---------------------------------------------------------------------------
# Pool scan fixtures + differential tests.
# ---------------------------------------------------------------------------


def _builtin_buffer() -> bytes:
    """Headers exercising every builtin tag with accept/reject variety."""
    buf = bytearray(b"\x00" * 0x800)
    # Proc: pass (nonpaged, big), reject (small), pass (free).
    put_header_x64(buf, 0x040, 0, 0x41, 2, b"Proc")
    put_header_x64(buf, 0x0C0, 0, 0x10, 2, b"Proc")
    put_header_x64(buf, 0x140, 0, 0x41, 0, b"Proc")
    # Pro\xe3 (pre-win8 process): pass nonpaged; reject paged.
    put_header_x64(buf, 0x1A0, 0, 0x41, 2, b"Pro\xe3")
    put_header_x64(buf, 0x200, 0, 0x41, 1, b"Pro\xe3")
    # Thre/Thr\xe5: pass + small reject.
    put_header_x64(buf, 0x260, 0, 0x40, 2, b"Thre")
    put_header_x64(buf, 0x2C0, 0, 0x05, 2, b"Thre")
    put_header_x64(buf, 0x320, 0, 0x40, 2, b"Thr\xe5")
    # File/Fil\xe5: pass; paged reject.
    put_header_x64(buf, 0x380, 0, 0x10, 2, b"File")
    put_header_x64(buf, 0x3E0, 0, 0x10, 1, b"File")
    put_header_x64(buf, 0x440, 0, 0x10, 2, b"Fil\xe5")
    # Muta/Mut\xe1: pass at exactly 64; reject below.
    put_header_x64(buf, 0x4A0, 0, 0x04, 2, b"Muta")
    put_header_x64(buf, 0x500, 0, 0x03, 2, b"Mut\xe1")
    # Driv/Dri\xf6: pass (0x10*0x10=256 >= 248), free pass.
    put_header_x64(buf, 0x560, 0, 0x10, 2, b"Driv")
    put_header_x64(buf, 0x5C0, 0, 0x10, 0, b"Dri\xf6")
    # MmLd: pass (0x05*0x10=80 >= 76).
    put_header_x64(buf, 0x620, 0, 0x05, 2, b"MmLd")
    # Symb/Sym\xe2: PAGED|FREE: pass paged; reject nonpaged.
    put_header_x64(buf, 0x680, 0, 0x05, 1, b"Symb")
    put_header_x64(buf, 0x6E0, 0, 0x05, 2, b"Symb")
    put_header_x64(buf, 0x740, 0, 0x05, 1, b"Sym\xe2")
    # CM10: PAGED|FREE, >= 800 (0x32*0x10=800): pass with odd PoolType 3.
    put_header_x64(buf, 0x7A0, 0, 0x32, 3, b"CM10")
    # Stray tag at offset 0: raw header offset -4 wraps to 0x7FC through the
    # layer address mask (0x7FF for a 0x800-byte buffer) and reads zeros, so
    # it fails the size check on both sides.
    buf[0x000:0x004] = b"Proc"
    return bytes(buf)


@pytest.fixture(scope="module")
def builtin_constraints():
    poolscanner = _poolscanner()
    return poolscanner.PoolScanner.builtin_constraints("nt_symbols")


@pytest.fixture(scope="module")
def builtin_layer(tmp_path_factory):
    tmp = tmp_path_factory.mktemp("pool_builtin")
    path = tmp / "pool.bin"
    path.write_bytes(_builtin_buffer())
    return str(path)


class TestPoolScan:
    def test_banner(self):
        print(f"\nvol_mojo backend under test: {BACKEND}")

    def test_builtin_x64_vista(self, builtin_constraints, builtin_layer):
        data = _builtin_buffer()
        expected = oracle_pool_hits(
            data, builtin_layer, builtin_constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(
            data, builtin_constraints, alignment=0x10, layout="x64", vista_semantics=True
        )
        assert got == expected
        offsets = [o for o, _ in got]
        assert 0x40 in offsets
        assert 0xC0 not in offsets  # undersized Proc must be rejected
        assert 0x7A0 in offsets  # paged CM10 with PoolType 3 (odd) passes

    def test_builtin_x64_win7_semantics(self, builtin_constraints, builtin_layer):
        """Pre-Vista pool-type mapping (paged == even non-zero PoolType)."""
        data = _builtin_buffer()
        expected = oracle_pool_hits(
            data, builtin_layer, builtin_constraints, "poolheader-x64-win7", False, 0x10
        )
        got = vol_mojo.scan_pool_headers(
            data, builtin_constraints, alignment=0x10, layout="x64", vista_semantics=False
        )
        assert got == expected
        offsets = [o for o, _ in got]
        # Under pre-Vista semantics the paged/nonpaged meaning swaps: the
        # PoolType-3 CM10 header is nonpaged now and must drop out, while
        # the PoolType-1 Pro\xe3 header becomes nonpaged and passes.
        assert 0x7A0 not in offsets
        assert 0x200 in offsets

    def test_x86_layout(self, tmp_path):
        poolscanner = _poolscanner()
        buf = bytearray(b"\x00" * 0x400)
        # BlockSize is 9-bit, PoolIndex 7-bit, PoolType 7-bit, alignment 8.
        put_header_x86(buf, 0x40, 0, 0x50, 2, b"Proc")  # 0x50*8=640 >= 600 pass
        put_header_x86(buf, 0x80, 0, 0x40, 2, b"Proc")  # 0x40*8=512 < 600 reject
        put_header_x86(buf, 0xC0, 3, 0x50, 1, b"CM10")  # 0x50*8=640 < 800 reject
        put_header_x86(buf, 0x100, 3, 0x64, 1, b"CM10")  # 0x64*8=800 pass paged
        data = bytes(buf)
        layer = tmp_path / "poolx86.bin"
        layer.write_bytes(data)
        constraints = poolscanner.PoolScanner.builtin_constraints("nt_symbols")
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x86", True, 0x8
        )
        got = vol_mojo.scan_pool_headers(
            data, constraints, alignment=0x8, layout="x86", vista_semantics=True
        )
        assert got == expected == [(0x40, b"Proc"), (0x100, b"CM10")]

    def test_x86_prevista_semantics(self, tmp_path):
        poolscanner = _poolscanner()
        buf = bytearray(b"\x00" * 0x400)
        put_header_x86(buf, 0x40, 0, 0x64, 2, b"CM10")  # even>0: paged pre-Vista
        put_header_x86(buf, 0x80, 0, 0x64, 1, b"CM10")  # odd: nonpaged pre-Vista
        data = bytes(buf)
        layer = tmp_path / "poolx86w7.bin"
        layer.write_bytes(data)
        constraints = poolscanner.PoolScanner.builtin_constraints("nt_symbols")
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x86", False, 0x8
        )
        got = vol_mojo.scan_pool_headers(
            data, constraints, alignment=0x8, layout="x86", vista_semantics=False
        )
        assert got == expected == [(0x40, b"CM10")]

    def test_longest_match_and_non_overlap(self, tmp_path):
        """Prefix-related tags pin the scanner's longest-match, leftmost
        non-overlapping semantics against the oracle's regex trie."""
        poolscanner = _poolscanner()
        constraints = [
            poolscanner.PoolConstraint(b"Ab", type_name="nt!_A"),
            poolscanner.PoolConstraint(b"Abcd", type_name="nt!_B"),
        ]
        buf = bytearray(b"\x00" * 0x100)
        buf[0x10:0x16] = b"AbcdAb"  # "Abcd" then "Ab" (no overlap)
        buf[0x30:0x34] = b"Abce"  # only "Ab" matches
        data = bytes(buf)
        layer = tmp_path / "overlap.bin"
        layer.write_bytes(data)
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(data, constraints, alignment=0x10)
        assert got == expected == [(0x0C, b"Abcd"), (0x10, b"Ab"), (0x2C, b"Ab")]

    def test_no_check_constraint_passes_every_tag_hit(self, tmp_path):
        """A tag-only constraint accepts every occurrence — including the
        one at offset 0, whose raw header offset (-4) the oracle normalizes
        through the layer address mask (0x7F for a 0x80-byte layer) to 0x7C
        instead of skipping it."""
        poolscanner = _poolscanner()
        constraints = [poolscanner.PoolConstraint(b"ZZZZ", type_name="nt!_Z")]
        buf = bytearray(b"\x00" * 0x80)
        buf[0x00:0x04] = b"ZZZZ"  # raw header at -4 -> masked to 0x7C
        buf[0x10:0x14] = b"ZZZZ"  # header at 0x0C -> pass (no checks at all)
        buf[0x20:0x24] = b"ZZZZ"
        data = bytes(buf)
        layer = tmp_path / "nocheck.bin"
        layer.write_bytes(data)
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(data, constraints)
        assert got == expected == [(0x7C, b"ZZZZ"), (0x0C, b"ZZZZ"), (0x1C, b"ZZZZ")]

    def test_size_and_index_bounds(self, tmp_path):
        poolscanner = _poolscanner()
        constraints = [
            poolscanner.PoolConstraint(
                b"Indx", type_name="nt!_I", size=(0x100, 0x200), index=(2, 4)
            )
        ]
        buf = bytearray(b"\x00" * 0x200)
        put_header_x64(buf, 0x40, 3, 0x10, 2, b"Indx")  # size/idx in range
        put_header_x64(buf, 0x80, 1, 0x10, 2, b"Indx")  # idx 1 < 2 reject
        put_header_x64(buf, 0xC0, 5, 0x10, 2, b"Indx")  # idx 5 > 4 reject
        put_header_x64(buf, 0x100, 3, 0x30, 2, b"Indx")  # 0x300 > 0x200 reject
        put_header_x64(buf, 0x140, 3, 0x08, 2, b"Indx")  # 0x80 < 0x100 reject
        put_header_x64(buf, 0x180, 4, 0x20, 2, b"Indx")  # 0x200 == max, idx 4 ok
        data = bytes(buf)
        layer = tmp_path / "bounds.bin"
        layer.write_bytes(data)
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(data, constraints, alignment=0x10)
        assert got == expected == [(0x40, b"Indx"), (0x180, b"Indx")]

    def test_integration_helper_returns_constraint_objects(self):
        data = _builtin_buffer()
        constraints = [
            PoolConstraint(
                b"Proc",
                size=(600, None),
                page_type=vol_mojo.PAGE_TYPE_NONPAGED | vol_mojo.PAGE_TYPE_FREE,
            )
        ]
        pairs = volatility3_integration.scan_like_pool_header_scanner(
            data, constraints, 0x10
        )
        assert [(off, bytes(c.tag)) for c, off in pairs] == [
            (0x40, b"Proc"),
            (0x140, b"Proc"),
        ]
        assert pairs[0][0] is constraints[0]

    def test_masked_negative_offset_wrapped_pass(self, tmp_path):
        """Tag at offset 0: raw header offset -4 normalizes to 0x7C (mask
        0x7F for a 0x80-byte layer); the wrapped header reads bytes at the
        buffer end and can pass the checks — it must be yielded, not
        skipped."""
        poolscanner = _poolscanner()
        constraints = [
            poolscanner.PoolConstraint(
                b"ZZZZ",
                type_name="nt!_Z",
                size=(600, None),
                page_type=poolscanner.PoolType.NONPAGED | poolscanner.PoolType.FREE,
            )
        ]
        buf = bytearray(b"\x00" * 0x80)
        buf[0x00:0x04] = b"ZZZZ"
        buf[0x7E] = 0x41  # BlockSize of the wrapped header -> 0x41*0x10 >= 600
        buf[0x7F] = 0x02  # PoolType: nonpaged (vista)
        data = bytes(buf)
        layer = tmp_path / "wrap_pass.bin"
        layer.write_bytes(data)
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(data, constraints, alignment=0x10)
        assert got == expected == [(0x7C, b"ZZZZ")]

    def test_masked_member_offset_wraps(self, tmp_path):
        """Tag at offset 2: header wraps to 0x7E and its BlockSize/PoolType
        member (relative offset 2) wraps again to buffer offset 0 — the
        oracle reads the header fields from the buffer start."""
        poolscanner = _poolscanner()
        constraints = [
            poolscanner.PoolConstraint(
                b"WWWW",
                type_name="nt!_W",
                size=(600, None),
                page_type=poolscanner.PoolType.NONPAGED | poolscanner.PoolType.FREE,
            )
        ]
        buf = bytearray(b"\x00" * 0x80)
        buf[0x02:0x06] = b"WWWW"
        buf[0x00] = 0x41  # BlockSize read through the double-wrapped member
        buf[0x01] = 0x02  # PoolType: nonpaged (vista)
        data = bytes(buf)
        layer = tmp_path / "wrap_member.bin"
        layer.write_bytes(data)
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(data, constraints, alignment=0x10)
        assert got == expected == [(0x7E, b"WWWW")]

    def test_masked_wrapped_read_out_of_buffer_skips(self, tmp_path):
        """Tag at offset 1: header wraps to 0x7D and its BlockSize/PoolType
        member lands at 0x7F — a 2-byte read there exceeds the 0x80-byte
        buffer, so the oracle skips the hit (InvalidAddressException)."""
        poolscanner = _poolscanner()
        constraints = [
            poolscanner.PoolConstraint(
                b"YYYY",
                type_name="nt!_Y",
                size=(600, None),
                page_type=poolscanner.PoolType.NONPAGED | poolscanner.PoolType.FREE,
            )
        ]
        buf = bytearray(b"\x00" * 0x80)
        buf[0x01:0x05] = b"YYYY"
        data = bytes(buf)
        layer = tmp_path / "wrap_invalid.bin"
        layer.write_bytes(data)
        expected = oracle_pool_hits(
            data, str(layer), constraints, "poolheader-x64", True, 0x10
        )
        got = vol_mojo.scan_pool_headers(data, constraints, alignment=0x10)
        assert got == expected == []

    def test_vol3_poolconstraint_objects_accepted_directly(self, builtin_constraints):
        """The oracle's own PoolConstraint objects duck-type through."""
        subset = [c for c in builtin_constraints if c.tag in (b"Proc", b"CM10")]
        data = _builtin_buffer()
        got = vol_mojo.scan_pool_headers(data, subset, alignment=0x10)
        assert got == [(0x40, b"Proc"), (0x140, b"Proc"), (0x7A0, b"CM10")]


# ---------------------------------------------------------------------------
# Cross-backend parity (native == fallback, independent of the oracle).
# ---------------------------------------------------------------------------


class TestCrossBackendParity:
    def test_walk_native_equals_fallback(self, small_tree):
        from vol_mojo import _native, _reference

        dat = small_tree["dat"]
        root = small_tree["root"]
        storage = len(dat) - 0x1000
        try:
            native = _native.walk_hive_native(dat, root, storage, 0)
        except _native.NativeUnavailable:
            pytest.skip("native kernel not built")
        finally:
            _native._LIB, _native._LIB_SOURCE = None, None
        fallback = _reference.walk_hive_reference(dat, root, storage, 0)
        assert native == fallback

    def test_scan_native_equals_fallback(self, builtin_constraints):
        from vol_mojo import _native, _reference, core

        data = _builtin_buffer()
        pairs = core._normalize_constraints(builtin_constraints)
        rows = [row for _, row in pairs]
        try:
            native = _native.scan_pool_headers_native(data, rows, 0x10, 0, True)
        except _native.NativeUnavailable:
            pytest.skip("native kernel not built")
        finally:
            _native._LIB, _native._LIB_SOURCE = None, None
        fallback = _reference.scan_pool_headers_reference(data, rows, 0x10, 0, True)
        assert native == fallback
