#!/usr/bin/env python3
"""Generate the bundled MAVLink common.xml dialect tables for pymavlink-mojo.

Dev-time tool (the generated file is committed; end users never run this).
Reads a MAVLink message-definition XML file (the protocol *specification*,
e.g. ``common.xml`` from the mavlink/mavlink project or the copy shipped
inside the ``pymavlink`` PyPI package), resolves its ``<include>`` chain, and
emits ``python/pymavlink_mojo/pymavlink_mojo/_dialect.py`` -- the flat
dialect lookup tables (per-message descriptors + per-field wire layouts).

The Mojo kernel is a generic table-driven decoder: the wrapper passes these
tables through the C ABI on every call (they are built once and cached), so
this single Python table is the one source of truth for the native kernel,
the pure-Python fallback, and the value-materializing wrapper.

Only protocol *facts* are extracted (message ids, names, field names, wire
types, array lengths, and the CRC-16/MCRF4XX "crc extra" constants computed
from the documented MAVLink serialization rules). No pymavlink (or other)
code is read, copied, or linked. The emitted tables are validated
black-box against the published pymavlink package by the differential test
suite (tests/test_pymavlink_differential.py::test_dialect_table_parity).

MAVLink wire-layout rules implemented here (MAVLink serialization guide):

  * Base (non-extension) fields are serialized in a stable descending sort
    by scalar type size (8, 4, 2, 1 bytes); extension fields follow in XML
    order. Arrays sort by their *element* size.
  * ``uint8_t_mavlink_version`` serializes as ``uint8_t``.
  * crc extra: CRC-16/MCRF4XX (init 0xFFFF) over ``NAME `` then, for every
    base field in *wire* order, ``TYPE NAME `` (with a trailing space each)
    plus the array length as one byte for array fields; the extra byte is
    ``(crc & 0xFF) ^ (crc >> 8)``.

Usage:

    python kernels/pymavlink/gen_tables_pymavlink.py \
        --xml /path/to/common.xml \
        --out-py python/pymavlink_mojo/pymavlink_mojo/_dialect.py
"""

from __future__ import annotations

import argparse
import os
# The only XML parsed here is the MAVLink dialect specification, a trusted,
# repo-vendored protocol-definition file (never user/network input), and
# ElementTree does not resolve external entities. nosemgrep: use-defused-xml-parse
import xml.etree.ElementTree as ET

# XML type -> (type code, scalar size, struct char)
# Type codes are shared with the Mojo kernel and the Python wrapper.
TYPES = {
    "char": (10, 1, "c"),
    "int8_t": (0, 1, "b"),
    "uint8_t": (1, 1, "B"),
    "uint8_t_mavlink_version": (1, 1, "B"),
    "int16_t": (2, 2, "h"),
    "uint16_t": (3, 2, "H"),
    "int32_t": (4, 4, "i"),
    "uint32_t": (5, 4, "I"),
    "float": (8, 4, "f"),
    "int64_t": (6, 8, "q"),
    "uint64_t": (7, 8, "Q"),
    "double": (9, 8, "d"),
}

HEADER = """\
# Generated by kernels/pymavlink/gen_tables_pymavlink.py from the MAVLink
# common.xml message-definition specification ({source_name}).
# Protocol facts only (ids, names, field layouts, crc-extra constants) --
# no code from pymavlink or any other project is included.
# Regenerate:  python kernels/pymavlink/gen_tables_pymavlink.py --xml <common.xml> ...
# Do not edit by hand.
"""


def accumulate(crc: int, byte: int) -> int:
    """One CRC-16/MCRF4XX step (MAVLink x25 checksum)."""
    tmp = byte ^ (crc & 0xFF)
    tmp = (tmp ^ (tmp << 4)) & 0xFF
    return ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xFFFF


def accumulate_str(crc: int, text: str) -> int:
    for ch in text:
        crc = accumulate(crc, ord(ch))
    return crc


class Field:
    __slots__ = ("name", "xml_type", "array_len", "extension")

    def __init__(self, name: str, xml_type: str, array_len: int, extension: bool):
        self.name = name
        self.xml_type = xml_type
        self.array_len = array_len
        self.extension = extension

    @property
    def code(self) -> int:
        return TYPES[self.xml_type][0]

    @property
    def size(self) -> int:
        return TYPES[self.xml_type][1]

    @property
    def struct_char(self) -> str:
        return TYPES[self.xml_type][2]


class Message:
    __slots__ = ("msgid", "name", "fields")

    def __init__(self, msgid: int, name: str, fields: list[Field]):
        self.msgid = msgid
        self.name = name
        self.fields = fields  # XML order

    @property
    def wire_fields(self) -> list[Field]:
        """Fields in serialization order: stable size-descending sort of the
        base fields, then extension fields in XML order."""
        base = [f for f in self.fields if not f.extension]
        exts = [f for f in self.fields if f.extension]
        return sorted(base, key=lambda f: -f.size) + exts

    @property
    def crc_extra(self) -> int:
        crc = 0xFFFF
        crc = accumulate_str(crc, self.name + " ")
        for f in self.wire_fields:
            if f.extension:
                continue
            t = "uint8_t" if f.xml_type == "uint8_t_mavlink_version" else f.xml_type
            crc = accumulate_str(crc, t + " ")
            crc = accumulate_str(crc, f.name + " ")
            if f.array_len:
                crc = accumulate(crc, f.array_len)
        return (crc & 0xFF) ^ (crc >> 8)

    @property
    def csize(self) -> int:
        """Full on-wire payload struct size in bytes (including extensions)."""
        total = 0
        for f in self.wire_fields:
            total += f.size * (f.array_len if f.array_len else 1)
        return total

    def wire_offsets(self) -> dict[int, int]:
        """XML field index -> byte offset of that field in the wire payload."""
        offsets: dict[int, int] = {}
        pos = 0
        for f in self.wire_fields:
            idx = self.fields.index(f)
            offsets[idx] = pos
            pos += f.size * (f.array_len if f.array_len else 1)
        return offsets


def load_messages(xml_path: str) -> list[Message]:
    """Parse a MAVLink XML dialect file, resolving <include> recursively."""
    seen: set[str] = set()
    out: list[Message] = []

    def walk(path: str) -> None:
        abspath = os.path.abspath(path)
        if abspath in seen:
            return
        seen.add(abspath)
        # Trusted, repo-vendored protocol spec only (never user/network input);
        # ElementTree resolves no external entities. nosemgrep: use-defused-xml-parse
        root = ET.parse(abspath).getroot()
        for inc in root.findall("include"):
            walk(os.path.join(os.path.dirname(abspath), inc.text))
        for m in root.findall("messages/message"):
            fields: list[Field] = []
            extension = False
            for child in m:
                if child.tag == "extensions":
                    extension = True
                    continue
                if child.tag != "field":
                    continue
                ftype = child.get("type")
                arr = child.get("array_length") or child.get("array")
                if ftype and "[" in ftype:
                    ftype, arr = ftype[:-1].split("[")
                if ftype not in TYPES:
                    raise ValueError(
                        f"unsupported field type {ftype!r} in message "
                        f"{m.get('name')} ({os.path.basename(abspath)})"
                    )
                fields.append(
                    Field(child.get("name"), ftype, int(arr) if arr else 0, extension)
                )
            out.append(Message(int(m.get("id")), m.get("name"), fields))

    walk(xml_path)
    by_id: dict[int, Message] = {}
    for msg in out:
        if msg.msgid in by_id:
            raise ValueError(f"duplicate message id {msg.msgid} ({msg.name})")
        by_id[msg.msgid] = msg
    return [by_id[k] for k in sorted(by_id)]


def emit_python(messages: list[Message], source_name: str) -> str:
    lines = [HEADER.format(source_name=source_name)]
    lines.append(
        '"""Bundled MAVLink common.xml dialect tables (generated; see header)."""\n'
    )
    lines.append("from __future__ import annotations\n")
    lines.append("# type codes: 0=i8 1=u8 2=i16 3=u16 4=i32 5=u32 6=i64 7=u64 8=f32 9=f64 10=char")
    lines.append("# field tuple: (name, type_code, array_len, wire_offset_bytes)")
    lines.append("# message tuple: (msgid, name, crc_extra, csize_bytes, fields)")
    lines.append("MESSAGES = (")
    for msg in messages:
        offsets = msg.wire_offsets()
        flds = ", ".join(
            f"({f.name!r}, {f.code}, {f.array_len}, {offsets[i]})"
            for i, f in enumerate(msg.fields)
        )
        # trailing comma keeps a single field a 1-tuple of tuples
        flds += ","
        lines.append(
            f"    ({msg.msgid}, {msg.name!r}, {msg.crc_extra}, {msg.csize}, ({flds})),"
        )
    lines.append(")")
    lines.append("")
    lines.append("BY_ID = {m[0]: m for m in MESSAGES}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--xml", required=True, help="path to common.xml")
    ap.add_argument("--out-py", required=True)
    args = ap.parse_args()

    messages = load_messages(args.xml)
    source_name = os.path.basename(args.xml)

    with open(args.out_py, "w") as fh:
        fh.write(emit_python(messages, source_name))
    n_fields = sum(len(m.fields) for m in messages)
    print(
        f"generated {len(messages)} messages ({n_fields} fields) from {args.xml}"
        f" -> {args.out_py}"
    )


if __name__ == "__main__":
    main()
