#!/usr/bin/env bash
# Regenerate langdetect_mojo/_uppercase_table.py: the Unicode "uppercase"
# codepoint ranges matching Python's str.isupper() for a single character
# (category Lu + Other_Uppercase, as exposed by the running interpreter).
#
# The reference detector's capitalword rule calls ch.isupper() on normalized
# characters; the Mojo kernel needs the same classification as a static table
# (shipped inside the profile blob it receives from the wrapper). The table is
# generated from the interpreter that runs this script and committed, so both
# the kernel and the pure-Python fallback classify exactly like the oracle.
#
# Run inside the repo pixi environment:
#   ~/.pixi/bin/pixi run bash scripts/gen_upper_table_langdetect.sh
set -euo pipefail

cd "$(dirname "$0")/.."

python - <<'EOF'
import sys
import unicodedata

out = "python/langdetect_mojo/langdetect_mojo/_uppercase_table.py"

cps = [c for c in range(sys.maxunicode + 1) if chr(c).isupper()]
ranges = []
start = prev = cps[0]
for c in cps[1:]:
    if c == prev + 1:
        prev = c
    else:
        ranges.append((start, prev))
        start = prev = c
ranges.append((start, prev))

with open(out, "w", encoding="utf-8") as f:
    f.write('"""Generated by scripts/gen_upper_table_langdetect.sh -- do not edit by hand.\n\n')
    f.write("Unicode uppercase codepoint ranges (inclusive), matching\n")
    f.write("``chr(c).isupper()`` of the generating interpreter:\n")
    f.write(f"- python: {sys.version.split()[0]}\n")
    f.write(f"- unicodedata: {unicodedata.unidata_version}\n")
    f.write(f"- ranges: {len(ranges)}\n")
    f.write('"""\n\n')
    f.write("UPPER_RANGES = (\n")
    for lo, hi in ranges:
        f.write(f"    (0x{lo:06X}, 0x{hi:06X}),\n")
    f.write(")\n")

print(f"wrote {out}: {len(ranges)} ranges over {len(cps)} codepoints")
EOF
